#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@author: houxue
@date: 2016/12/8
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        res = 0

        for c in ''.join([s, t]):
            res ^= ord(c)

        return chr(res)


if __name__ == "__main__":
    solution = Solution()
    a = 'abcd'
    b = 'abcde'
    print(solution.findTheDifference(a, b))
